### ISSUE TITLE
Internal Server Error when adding the same products twice

### ISSUE THREAD

**Issue by jameslindeman** [engram-design/MultiAdd#4]
I’ve only tested this with Commcerce 1.0.1186 (not supported with this version I know) but if the same products are submitted  twice it causes an Internal Server Error. For example, add multiple products with a redirect to the cart then go back to the previous page and add the same products again.

**Comment by bossanova808** [comment]
Can not confirm.  I do this all the time, with latest commerce and craft.
 I suspect an issue with your forms - maybe take it up in slack?

**Comment by engram-design** [comment]
Not sure if this was resolved or not, but very hesitant to support older versions of Commerce. But by all means, chase either @bossanova808 or myself up in Slack about it!

**Comment by jameslindeman** [comment]
Thanks for looking into it. I couldn’t find the culprit so closed it. I’ll let you know if I find anything.
